name: Maven Package [ MAIN ]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven [ Client ] 
      run: cd Client && mvn clean package
    - name: Build with Maven [ Server ]
      run: cd ../Server && mvn clean package
